### ISSUE TITLE
Max/Min value of brisque

### ISSUE THREAD

**Issue by jasony93** [rehanguha/brisque#10]
Hello, Thank you for providing this amazing repository.

I was wondering if there are min and max values for brisque score.

Thanks in advance.

**Comment by rehanguha** [comment]
Thank you for using the package.
The BRISQUE score is usually ranges in [0, 100]. Lower values of score reflect better perceptual quality of image with respect to the input model.
But, In some cases it can go above 100 but never below... Most of the cased its [0,100].

**Comment by devanshkhandekar** [comment]
I was testing on my images, and the score returned value -4. How to meaningfully clip those values between 0-100
