### ISSUE TITLE
AttributeError: Module 'scipy' has no attribute 'ndarray'

### ISSUE THREAD

**Issue by magallardoacn** [rehanguha/brisque#13]
![image](https://github.com/rehanguha/brisque/assets/157500067/0f2cb511-0ee2-4aa9-8d43-0edf19f37192)

**Describe the bug**

**To Reproduce**
pip install brisque numpy scipy scikit-image Pillow

import imquality.brisque as brisque
import PIL.Image
path = 'page_22.png'
img = PIL.Image.open(path)
brisque.score(img)

**Expected behavior**

N/A

**Screenshots**
up

**Log**

AttributeError: Module 'scipy' has no attribute 'ndarray'
**Additional context**

**Comment by rehanguha** [comment]
@magallardoacn... Try to install the [requirements.txt](https://github.com/rehanguha/brisque/blob/master/requirements.txt) given in the main repo.

Duplicate Issue: https://github.com/rehanguha/brisque/issues/12

**Comment by rehanguha** [comment]
@magallardoacn as per your code you are using a different package i.e. `imquality` and the name of my package is `brisque`.
