### ISSUE TITLE
Adding Ndarray image as input

### ISSUE THREAD

**Issue by Andrew-Ma-2001** [rehanguha/brisque#8]
Hi, wonderful job.
   I was wondering if adding an input of Ndarray image would be more useful in practice. I personally use brisque to read images from videos, so that in this way using Ndarray image as input seems more friendly to users.
  No worries, I already change the source code to achieve reading Ndarray, but I think for further improvement, maybe my suggestion could be helpful.

**Comment by rehanguha** [comment]
Hi, Thank you for your feedback.
I feel it will be a great addition... It will be great if you can push a
quick PR and keep and argument to toggle the type. I feel it will be a
great addition.
